# fly.toml app configuration file generated for laruina-main-tv on 2023-09-01T10:52:19-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "laruina-main-tv"
primary_region = "scl"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
